// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"time"
)

type Balance struct {
	ID       int32
	Username string
	Coins    int32
}

type History struct {
	ID       int32
	Username string
	FromUser string
	ToUser   string
	Amount   int32
	SentAt   time.Time
}

type Inventory struct {
	ID       int32
	Username string
	Type     string
	Quantity int32
	BoughtAt time.Time
}

type Merch struct {
	ID    int32
	Type  string
	Price int32
}

type User struct {
	ID        int32
	Username  string
	Password  string
	CreatedAt time.Time
}
