# ==============================================================================

#  Local commands

.PHONY: test
test:	# Execute the unit tests
	go test -count=1 -v -timeout 30s -coverprofile cover.out ./...

.PHONY: ginkgo
ginkgo:	# Execute the ginkgo unit tests
	ginkgo ./...

.PHONY: tidy
tidy:	# Cleanup go.mod
	go mod tidy

.PHONY: fmt
fmt:	# Format *.go and *.proto files using gofmt and clang-format
	gofmt -w .
	goimports -w .

.PHONY: cover
cover:	# Show the cover report
	go tool cover -html cover.out

.PHONY: update
update:	# Update dependencies as recorded in the go.mod and go.sum files
	go list -m -u all
	go get -u ./...
	go mod tidy